import { workflowStages } from "../data";
import type { Business, DocumentException, OpenTask, Stage } from "../types";
import { Badge, Metric, PageHeader, StageBadge } from "./Primitives";

type OpenBusiness = (id: string) => void;
type MoveStage = (id: string, stage: Stage) => void;

export function Dashboard({ businesses, tasks, onOpen }: { businesses: Business[]; tasks: OpenTask[]; onOpen: OpenBusiness }) {
  const active = businesses.filter((business) => !["Funded", "Declined"].includes(business.stage));
  const underwriting = businesses.filter((business) => business.stage === "Underwriting");
  return <section className="page"><PageHeader eyebrow="Capital operations" title="Today’s funding desk" description="Prioritize decisions, unblock documents, and keep every borrower moving." action={<button className="secondary">Export view</button>} /><div className="metricGrid"><Metric label="Active applications" value={String(active.length)} note="Across all advisers" /><Metric label="Decisions due today" value={String(underwriting.length)} note="Human review required" /><Metric label="Offers awaiting response" value={String(businesses.filter((business) => business.stage === "Offer sent").length)} note="Track expiry and consent" /><Metric label="Open work items" value={String(tasks.length)} note="Compliance tasks included" /></div><div className="dashboardGrid"><section className="card"><div className="sectionHeading"><div><p>Service attention</p><h2>Applications requiring action</h2></div><Badge>{underwriting.length} urgent</Badge></div><table className="dataTable"><thead><tr><th>Business</th><th>Stage</th><th>Requested</th><th>Next action</th></tr></thead><tbody>{active.map((business) => <tr key={business.id} onClick={() => onOpen(business.id)}><td><strong>{business.name}</strong><small>{business.owner}</small></td><td><StageBadge stage={business.stage} /></td><td>{business.requested}</td><td>{business.decisionDue}</td></tr>)}</tbody></table></section><section className="card"><div className="sectionHeading"><div><p>Work queue</p><h2>Assigned to your desk</h2></div></div>{tasks.slice(0, 5).map((task) => <button className="queueItem" key={task.id} onClick={() => onOpen(task.businessId)}><span>○</span><div><strong>{task.title}</strong><small>{task.business} · Due {task.due}</small></div></button>)}</section></div></section>;
}

export function Pipeline({ businesses, onOpen, onMove }: { businesses: Business[]; onOpen: OpenBusiness; onMove: MoveStage }) {
  const columns: Stage[] = ["Pre qualified", "Documents", "Underwriting", "Offer sent", "Funding"];
  return <section className="page"><PageHeader eyebrow="Application operations" title="Funding pipeline" description="Move applications through a controlled and visible workflow." action={<button className="secondary">Filter applications</button>} /><div className="kanban">{columns.map((column) => <section key={column}><header><span>{column}</span><b>{businesses.filter((business) => business.stage === column).length}</b></header>{businesses.filter((business) => business.stage === column).map((business) => <article key={business.id}><button onClick={() => onOpen(business.id)}><strong>{business.name}</strong><small>{business.industry}</small></button><div><span>{business.requested}</span><Badge>{business.risk}</Badge></div><p>{business.decisionDue}</p><button className="textAction" onClick={() => onMove(business.id, workflowStages[workflowStages.indexOf(column) + 1])}>Advance</button></article>)}</section>)}</div></section>;
}

export function WorkQueue({ tasks, onOpen, onComplete }: { tasks: OpenTask[]; onOpen: OpenBusiness; onComplete: (businessId: string, taskId: string) => void }) {
  return <section className="page"><PageHeader eyebrow="Work management" title="Operations queue" description="Tasks created by people and approved workflows with clear owners and due dates." action={<Badge>{tasks.length} open</Badge>} /><section className="card"><table className="dataTable"><thead><tr><th></th><th>Task</th><th>Business</th><th>Category</th><th>Due</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><button className="check" onClick={() => onComplete(task.businessId, task.id)} aria-label={`Complete ${task.title}`} /></td><td><strong>{task.title}</strong></td><td><button className="textAction" onClick={() => onOpen(task.businessId)}>{task.business}</button></td><td><Badge>{task.type}</Badge></td><td>{task.due}</td></tr>)}</tbody></table></section></section>;
}

export function DocumentExceptions({ docs, onOpen }: { docs: DocumentException[]; onOpen: OpenBusiness }) {
  return <section className="page"><PageHeader eyebrow="Evidence management" title="Document exceptions" description="Prioritize missing, unverified, and expired evidence before underwriting or funding." action={<Badge>{docs.length} need attention</Badge>} /><section className="card"><table className="dataTable"><thead><tr><th>Document</th><th>Borrower business</th><th>Status</th><th>Updated</th><th>Owner</th></tr></thead><tbody>{docs.map((doc) => <tr key={doc.id} onClick={() => onOpen(doc.businessId)}><td><strong>{doc.name}</strong></td><td>{doc.business}</td><td><Badge>{doc.status}</Badge></td><td>{doc.updated}</td><td>{doc.owner}</td></tr>)}</tbody></table></section></section>;
}

export function CapitalPartners() {
  const partners = [["Cortada Direct", "Working capital, term loans, and lines of credit", "18", "3.8 hours", "92%"], ["Atlas Capital", "Term loans and refinance", "6", "5.2 hours", "78%"], ["Aventura Funding", "Working capital", "4", "6.1 hours", "71%"]];
  return <section className="page"><PageHeader eyebrow="Controlled distribution" title="Capital partners" description="Track criteria, submissions, response time, and outcomes without losing the borrower record." action={<button className="primary">Add partner</button>} /><section className="card"><table className="dataTable"><thead><tr><th>Partner</th><th>Product appetite</th><th>Open submissions</th><th>Average response</th><th>Offer rate</th></tr></thead><tbody>{partners.map((partner) => <tr key={partner[0]}><td><strong>{partner[0]}</strong><small>Approved partner profile</small></td><td>{partner[1]}</td><td>{partner[2]}</td><td>{partner[3]}</td><td><Badge>{partner[4]}</Badge></td></tr>)}</tbody></table></section><div className="infoBanner"><strong>Data sharing gate</strong><span>Production submissions must verify borrower authorization, complete package, sharing purpose, and a transmission audit event.</span></div></section>;
}

export function Reports({ businesses }: { businesses: Business[] }) {
  return <section className="page"><PageHeader eyebrow="Operating intelligence" title="Funding performance" description="Decision speed, portfolio flow, and operational friction built from CRM workflow data." action={<button className="secondary">Configure report</button>} /><div className="metricGrid"><Metric label="Applications received" value={String(businesses.length)} note="Current demo portfolio" /><Metric label="Funded applications" value={String(businesses.filter((business) => business.stage === "Funded").length)} note="Tracks funding status" /><Metric label="Median decision time" value="8.6 hours" note="Target under 12 hours" /><Metric label="Document completion" value="71%" note="Before underwriting" /></div><div className="reportGrid"><section className="card"><p className="eyebrow">Pipeline mix</p><h2>Applications by stage</h2>{workflowStages.slice(0, 6).map((stage) => { const count = businesses.filter((business) => business.stage === stage).length; return <div className="bar" key={stage}><span>{stage}</span><i><b style={{ width: `${Math.max(count * 25, 4)}%` }} /></i><strong>{count}</strong></div>; })}</section><section className="card"><p className="eyebrow">Compliance view</p><h2>Evidence and consent controls</h2><div className="compliance"><div><span>✓</span><strong>Credit authorizations recorded</strong><b>3 of 4</b></div><div><span>✓</span><strong>Documents verified</strong><b>8 of 11</b></div><div><span>!</span><strong>Applications with open review items</strong><b>3</b></div></div></section></div></section>;
}
